version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
        - postgres
    volumes:
    - ./log:/usr/app/log
    - ./src:/usr/app/src
    environment:
        - PORT=${PORT}
  postgres:
      build: ./db/
      environment:
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
