version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
        - postgres
    environment:
        - PORT=${PORT}
  postgres:
      build: ./db/
      volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
      environment:
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
